version: '3.8'

services:
  echobridge:
    build: .
    ports:
      - '3000:3000'
    environment:
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
